language: clojure
jdk:
- oraclejdk8
install:
# Install Emacs24
- sudo apt-add-repository -y ppa:cassou/emacs
- sudo apt-get update
- sudo apt-get install -y emacs24 emacs24-el emacs24-common-non-dfsg

# Install Org-Mode
- mkdir ~/elisp
- git clone git://orgmode.org/org-mode.git ~/elisp/org-mode
- cd ~/elisp/org-mode && make autoloads

# go back to project directory
- cd 

# Tangle clojure files
- ./org/tangle.sh ./org/pva-parrot.org

# Install Boot
- wget https://github.com/boot-clj/boot/releases/download/2.0.0-rc12/boot.sh
- mv boot.sh boot && chmod a+x boot && sudo mv boot /usr/local/bin

# back to project directory and start tests
- cd /home/ubuntu/src/github.com/PVA-Parrot/PVA-Parrot
script: ./boot run-tests
